spring:
  profiles:
    active: prod
---
# profiles value 할당 (방법1)
# java -jar 파일명.jar --spring.profiles.active=profiles값 (택1)
# java -Dspring.profiles.active=profiles값 -jar 파일명.jar (택2)
# profiles value 할당 (방법2)
# Edit Configurations > Run/Debug Configurations > Active Profiles 값 할당
# .\gradlew build -x test -Pprofile=prod
# 빌드시 테스트 진행하지 않고 prod 로 실행
---