server:
  port: 8080
  servlet:
    context-path: /blog-api
spring:
  datasource:
    #driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://127.0.0.1:3306/shkim30
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://127.0.0.1:3306/shkim30
    username: root
    password: root
  #jpa:
  #  hibernate:
  #    ddl-auto: create
  #  properties:
  #    hibernate:
  #      format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  config-location: classpath:mybatis/configuration.xml

