server:
  port: 80
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-message: on_param # no, on_param, always
    include-stacktrace: on_param  # no, on_param, always
    include-binding-errors: on_param  # no, on_param, always
spring:
  profiles: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/shkim30
    username: root # 알맞게 수정필요
    password: root # 알맞게 수정필요
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  config-location: classpath:mybatis/configuration.xml